"""Updated file database

Revision ID: 00f5588a0094
Revises: 07726143a2b3
Create Date: 2018-11-24 01:09:29.669118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f5588a0094'
down_revision = '07726143a2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_file_filename'), 'file', ['filename'], unique=False)
    op.drop_index('ix_file_timestamp', table_name='file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_file_timestamp', 'file', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_file_filename'), table_name='file')
    # ### end Alembic commands ###
