"""Added path

Revision ID: 481a28e75937
Revises: abe50374d225
Create Date: 2018-12-15 21:24:18.562361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481a28e75937'
down_revision = 'abe50374d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('path', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'token', 'file', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.drop_column('file', 'path')
    # ### end Alembic commands ###
