"""AvatarId & FilesReadable

Revision ID: 881c8eb5d095
Revises: c3de5a3a8b71
Create Date: 2018-11-30 16:28:49.075975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881c8eb5d095'
down_revision = 'c3de5a3a8b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('readable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'readable')
    # ### end Alembic commands ###
