"""Created file types

Revision ID: aba1335a28ed
Revises: 00f5588a0094
Create Date: 2018-11-24 22:50:27.539671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aba1335a28ed'
down_revision = '00f5588a0094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'type')
    # ### end Alembic commands ###
