"""Added avatar table

Revision ID: c3de5a3a8b71
Revises: 2a96beaf9622
Create Date: 2018-11-27 15:21:13.727414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3de5a3a8b71'
down_revision = '2a96beaf9622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('avatar', sa.String(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('avatar')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('avatar')
    # ### end Alembic commands ###
